[[redirects]]
  from = "/wc-landing.js"
  to = "https://mf-landing.netlify.app/wc-landing.js"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"